### PR TITLE
JCRVLT-434 classifier support in all mojos

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
@bpauli Please check this improved PR and also check out in https://github.com/apache/jackrabbit-filevault-package-maven-plugin/pull/41/files#diff-431deac1b75485f1b3c6cc64fd17b4f6 how to build two packages in one execution.

**Comment by bpauli** [comment]
@LGTM! Thank you!

**Comment by cjelger** [comment]
@kwin Nice work, I think many of us have been looking for that extra option. Do you have any plan for a new release any time soon? Thank you.

**Comment by bpauli** [comment]
@tripodsan maybe you can help with the release please?

**Comment by kwin** [comment]
Please use the mailing list for release requests, not PRs!

**Pull request closed without merging**
